name: themadgerman
favicon: null
layout_spectrum: 0.5218814483378083
typography_spectrum: 0.6105922544375062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9089894311036915
  lightness: 0.10122934821993113
  saturation: 0.36940062046051025
  rhythmicContrast: 0.3102904590778053
purpose: []
